### ISSUE TITLE
Return Result Object From Upload

### ISSUE THREAD

**Issue by MelbourneDeveloper** [supabase-community/storage-csharp#11]
# Feature request

The `Upload` method on `IStoreFileApi` needs an `IsSuccess` flag and an error message. 

## Is your feature request related to a problem? Please describe.

I'm uploading files to a bucket, and the method is returning the path. However, the file never shows up in the bucket. Actually, I cannot upload files at all with this method. Clearly, the file is failing to upload, but I have no idea why.

## Describe the solution you'd like

The `Upload` method should return a response model, like that in the other clients, and it should give an error to explain what went wrong. I've burned hours trying to upload a file and I still have no idea why it never shows up on the other side. It's probably just a permissions issue, but I have no feedback to tell me. 

## Describe alternatives you've considered

I can only think of using the JavaScript client instead.

**Comment by MelbourneDeveloper** [comment]
@acupofjose Thankyou very much

**Comment by acupofjose** [comment]
@MelbourneDeveloper okay. I implemented it a little differently than you requested, but the `Upload` and `Download` methods will now throw exceptions if you are unauthorized to access them. 

If it returns the path, you should now be confident in the path existing. I will be creating a new minor release with the updates here shortly before pushing it to the main `supabase-csharp` repo.

Again, apologies for the delay. But thank you for the issue, helpful bug catching here.
