### ISSUE TITLE
Upload progress appears to be 0 or 100 with nothing inbetween

### ISSUE THREAD

**Issue by Kuffs2205** [supabase-community/storage-csharp#3]
Running the following code:

	Private Async Sub test()
		Dim client = Await SupabaseManager.GetInstance.GetClient
		Dim storageBucket = client.Storage.From("testbucket")
		Dim result = Await storageBucket.Upload("c:\test.txt", "test.txt",, AddressOf ProgressStatus)
	End Sub
	Private Sub ProgressStatus(sender As Object, e As Single)
		Debug.WriteLine($"{Date.Now: dd MMM yyyy HH:mm:ss.fff} : Upload Status = {e}%")
	End Sub

Produces the following output.

 28 Feb 2023 15:33:36.186 : Upload Status = 0%
 28 Feb 2023 15:33:36.186 : Upload Status = 0%
 28 Feb 2023 15:33:36.214 : Upload Status = 0%
 28 Feb 2023 15:33:36.215 : Upload Status = 0%
--snipped many lines --
 28 Feb 2023 15:33:53.998 : Upload Status = 0%
 28 Feb 2023 15:33:54.004 : Upload Status = 0%
 28 Feb 2023 15:33:54.006 : Upload Status = 0%
 28 Feb 2023 15:33:54.010 : Upload Status = 0%
 28 Feb 2023 15:33:54.013 : Upload Status = 100%

Possibly it is being cast to an Int at some point in the process?

**Comment by acupofjose** [comment]
Out of curiosity - could you try it with a larger file and see if it makes a difference?

**Comment by Kuffs2205** [comment]
I doubled the size to 40Mb. Same result. Approx 35 seconds to upload.

 28 Feb 2023 17:01:11.765 : Upload Status = 0%
 28 Feb 2023 17:01:11.768 : Upload Status = 0%
 28 Feb 2023 17:01:11.770 : Upload Status = 0%
Snip
 28 Feb 2023 17:01:46.437 : Upload Status = 0%
 28 Feb 2023 17:01:46.442 : Upload Status = 0%
 28 Feb 2023 17:01:46.444 : Upload Status = 100%

**Comment by Kuffs2205** [comment]
No problem. Just trying to be helpful by reporting what i find.

This library has been a lifesaver for me.

**Comment by acupofjose** [comment]
Available in v1.2.5!
