### ISSUE TITLE
Anon key gives 404 result on public buckets

### ISSUE THREAD

**Issue by Kuffs2205** [supabase-community/storage-csharp#7]
I'm not sure if this is the normal behaviour or not as I'm not yet familiar enough with the Storage system but I would expect to have full read access to a public bucket when using the anon key.

When trying to download a file, the client is giving me a 404 but switching it with the Admin key works fine.

`{"statusCode":"404","error":"Not found","message":"The resource was not found"}`

**Comment by acupofjose** [comment]
You're correct! Missed that in the implementation compared to the JS client. The `Download` method can only be used behind private buckets. I've added a `DownloadPrivateFile` in v1.2.10!
