### ISSUE TITLE
Socket Exhaustion Starvation Issue

### ISSUE THREAD

**Issue by Kuffs2205** [supabase-community/storage-csharp#8]
Just a heads up.

The library is susceptible to Socket Exhaustion issues due to creating a new HttpClient for each request.  I did hit it myself but it is easy enough to duplicate.

https://www.aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by acupofjose** [comment]
Good call! I'll get to work on a fix. Appreciate it!

**Comment by acupofjose** [comment]
Available in v1.3.0!
